<%@ Page Language="C#" AutoEventWireup="true" CodeFile="RoleTree.aspx.cs" Inherits="Right_RoleTree" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>菜单权限分配</title>
   <meta http-equiv="Pragma"   content="no-cache" />   
   <meta    http-equiv="Cache-Control"   content="no-cache"/>   
   <meta    http-equiv="Expires"   content="0"/>  
</head>
<script type="text/javascript">
function postBackByObject()
{
    var o = window.event.srcElement;
    if (o.tagName == "INPUT" && o.type == "checkbox")
    {
        __doPostBack("","");
    } 
 }

 /*function OnTreeNodeChecked() 
{
    var ele = window.event.srcElement; 
    if(ele.type=='checkbox') 
     { 
        var childrenDivID = ele.id.replace('CheckBox','Nodes'); 
        var div = document.getElementById(childrenDivID); 
        if(div==null)return; 
        var checkBoxs = div.getElementsByTagName('INPUT'); 
        for(var i=0;i<checkBoxs.length;i++) 
        { 
            if(checkBoxs[i].type=='checkbox') 
                 checkBoxs[i].checked=ele.checked; 
        } 
    } 
}*/
</script>

<body style=" background-color:#E3EFFF;">
    <form id="form1" runat="server">
    <div>
        <table>
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td style="width: 100%">
                    <asp:Label ID="Label1" runat="server" Text="Label" ></asp:Label> <asp:Button ID="Button1" runat="server"  OnClick="Button1_Click" Text="保存" Width="102px" />
                </td>
                <td>
               
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td colspan="5">
                    <asp:TreeView ID="TreeView1" runat="server" ShowCheckBoxes="All" OnSelectedNodeChanged="TreeView1_SelectedNodeChanged1" ShowLines="True" AutoGenerateDataBindings="False" onclick="postBackByObject()" OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged">
                    </asp:TreeView>
                </td>
            </tr>
            <tr>
                <td>
                </td>
                <td>
                </td>
                <td style="width: 217px">
                </td>
                <td>
                    </td>
                <td>
                </td>
            </tr>
        </table>
    
    </div>
    </form>
</body>
</html>
