<%@ Page Language="C#" AutoEventWireup="True" EnableViewState="false" CodeFile="Left.aspx.cs"
    Inherits="Left" %>

<!-- 影响页面高度
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>无标题页</title>
    <link href="App_Themes/Default/StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body class="tree_bgcolor" leftmargin="0" topmargin="0">
    <form id="form1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server">
    </asp:ScriptManager>
    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
           <%-- <asp:ImageButton ID="ImageButton1" runat="server" onclick="lb_btn_sample_Click" ImageUrl="~/images/top1.GIF"/>
            <asp:ImageButton ID="ImageButton2" runat="server" onclick="lb_tbn_file_Click" 
                ImageUrl="~/images/top2.GIF" Height="32px"/>--%>
           <%-- <table border="0" cellpadding="0" cellspacing="0" style="width: 150px">
            <tr><td>
            <asp:LinkButton ID="lb_btn_sample" runat="server" onclick="lb_btn_sample_Click" CssClass="btn" Width="75px">样品报告</asp:LinkButton>
           </td><td> <asp:LinkButton ID="lb_tbn_file" runat="server" onclick="lb_tbn_file_Click" CssClass="btn" Width="75px">文件管理</asp:LinkButton>
           </td></tr> </table>--%>
            <asp:Panel ID="panel_sample" runat="server" Visible="true">
                <table height="96%" border="0" cellpadding="0" cellspacing="0" style="width: 150px">
                    <tr>
                        
                        <td height="27" class="left1_bgimage" valign="bottom" style="width: 150px">
                            &nbsp;
                            <asp:LinkButton ID="ExpandButton" runat="server" OnCommand="Button_Command" CommandName="Expand"
                                Text='<font color="#E78A29">[</font>展开<font color="#E78A29">]</font>' Font-Size="10pt"></asp:LinkButton>
                            <asp:LinkButton ID="CollapseButton" runat="server" OnCommand="Button_Command" CommandName="Collapse"
                                Text='<font color="#E78A29">[</font>收缩<font color="#E78A29">]</font>' Font-Size="10pt"></asp:LinkButton>
                        </td>
                    </tr>
                    <tr height="100%">
                        <td height="100%" valign="top" class="leftbj_bgimage" style="width: 150px">
                            <asp:TreeView ID="TreeView1" runat="server" ShowLines="True" ShowExpandCollapse="true" 
                                Width="100%" Height="100%" Target="mainFrame">
                                <SelectedNodeStyle BorderColor="#FF6699" BorderStyle="Double" BorderWidth="1px" />
                            </asp:TreeView>
                        </td>
                    </tr>
                    <tr>
                        <td height="19" class="left2_bgimage" valign="bottom" style="width: 150px">
                        </td>
                    </tr>
                </table>
            </asp:Panel>
            <asp:Panel ID="panel_file" runat="server" Visible="false">
                <table height="96%" border="0" cellpadding="0" cellspacing="0" style="width: 150px">
                   <tr><td> <asp:Label ID="Label2" runat="server" Text="目录名：" Width="64px"></asp:Label>
                        <asp:TextBox ID="TextBox_Catalog" runat="server" Width="96px"></asp:TextBox><br />
                        <asp:Button ID="Button_AddCatalog" runat="server" OnClick="Button2_Click" Text="添加目录" CssClass="buttonstyle" />
                        <asp:Button ID="Button_Delete" runat="server" OnClick="Button3_Click" Text="删除" Width="79px" CssClass="buttonstyle" /></td></td></tr>
                    <tr height="100%">
                        <td height="100%" valign="top" class="leftbj_bgimage" style="width: 150px">
                            <asp:TreeView ID="TreeView2" runat="server" Height="169px" Width="169px" AutoGenerateDataBindings="False" OnSelectedNodeChanged="TreeView2_SelectedNodeChanged" ImageSet="WindowsHelp">
                            <ParentNodeStyle Font-Bold="False" />
                            <HoverNodeStyle Font-Underline="True" ForeColor="#6666AA" />
                            <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" HorizontalPadding="0px"
                                VerticalPadding="0px" />
                            <NodeStyle Font-Names="Tahoma" Font-Size="8pt" ForeColor="Black" HorizontalPadding="5px"
                                NodeSpacing="0px" VerticalPadding="1px" />
                        </asp:TreeView>
                        </td>
                    </tr>
                    <tr>
                        <td height="19" class="left2_bgimage" valign="bottom" style="width: 150px">
                        </td>
                    </tr>
                </table>
            </asp:Panel>
        </ContentTemplate>
    </asp:UpdatePanel>
    &nbsp;&nbsp;
    </form>
</body>
</html>
